### ISSUE TITLE
Compatibility with other common software licenses?

### ISSUE THREAD

**Issue by nogweii** [kemitchell/slipstream#14]
I haven't read this in too much detail, so apologies if I've missed this already.

It's be useful to include a FAQ document, or similar, describing if it is OSI-approved and how it interacts with the GPL.

**Comment by evaryont** [comment]
Of course, a lot of this depends on the choices made in creating the contract in the first place, so perhaps the possibilities are too numerous to adequately summarize?

**Comment by kemitchell** [comment]
@evaryont, thank you for your comment. I'm sorry that I'm not sure exactly how to go about addressing it.

Long and short, this is not the kind of license document that OSI would approve or refuse to approve. It's intentionally written for proprietary software, which may or may not utilize Open Source work.  Companies writing software services need to think about the GPL and all the other licenses for Open Source software that they use. But this terms, for their proprietary product, only concern Open Source code insofar as the product is licensed for installation by the customer, and the customer will need to download or use Open Source code and tools to do so.
